routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/master', function () {
    return view('layouts.master');
});

Route::get('/manageusers', function () {
    return view('manageusers');
});


Route::get('/transaksi', function () {
    return view('transaksi');
});


//ITEM
Route::get('/viewitem','ItemController@view');
Route::post('/additem','ItemController@add');
Route::get('/edititem/{id}','ItemController@edit');
Route::post('/updateitem/{id}','ItemController@update');
Route::get('/deleteitem/{id}','ItemController@delete');

//MAKANAN
Route::get('/viewmakanan','MakananController@view');
Route::post('/addmakanan','MakananController@add');
Route::get('/editmakanan/{id}','MakananController@edit');
Route::post('/updatemakanan/{id}','MakananController@update');
Route::get('/deletemakanan/{id}','MakananController@delete');

//MINUMAN
Route::get('/viewminuman','MinumanController@view');
Route::post('/addminuman','MinumanController@add');
Route::get('/editminuman/{id}','MinumanController@edit');
Route::post('/updateminuman/{id}','MinumanController@update');
Route::get('/deleteminuman/{id}','MinumanController@delete');

Route::get('/daftarmenu',['uses'=>'ItemController@loadmenu','as'=>'item.index']);

Auth::routes();

//<!-- AAAAAAUUUUUUUUUTTTTTTTHHHHHHHHHHH -->
Auth::routes();

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');

Route::get('/', 'HomeController@index')->name('home');

//cart

Route::get('addtocart/{id}',['uses'=> 'ItemController@GetAddToCart', 'as' => 'item.addToCart']);
Route::get('reducetocart/{id}',['uses'=> 'ItemController@GetReduceToCart', 'as' => 'item.reduceToCart']);

Route::get('/shoppingcart',['uses'=> 'ItemController@GetCart', 'as' => 'item.shoppingCart']);

Route::get('/checkout',['uses'=> 'ItemController@GetCheckout', 'as' => 'checkout']);
Route::post('/postcheckout',['uses'=> 'ItemController@postCheckout', 'as' => 'checkout']);

Route::get('/pesanan','ItemController@viewPesanan');
Route::get('/history','ItemController@viewTransaksi');
Route::post('/verifikasi','ItemController@Verivikasi');
Route::post('/verifikasi{id}','ItemController@DeleteVerivikasi');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Resto UwU -@yield('title')</title>

  <link rel="shortcut icon" href="../../dist/img/icon.png">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">
  
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-light navbar-orange">
    <!-- Left navbar links 
    -->
    
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
      </li>
    </ul>

    @hasrole('Pelanggan')
    <a href="{{route('item.shoppingCart')}}" role="button" class="btn btn-outline-dark" style="margin-left: 3rem" >
                                    
      <i class="fas ion-ios-cart"></i> <b> Pesanan Anda  </b> <span class="badge badge-secondary">{{Session::has('cart')?Session::get('cart')->totalQty : ''}}</span>
    </a>
    @endrole
    <!-- SEARCH FORM 
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form> -->

    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    
            <i class="fas ion-person"></i> <b> {{ Auth::user()->name }} </b> <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>

  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-orange elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link navbar-orange">
      <img src="../../dist/img/icon.png"
           alt="UwU Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Restoran UwU</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="../../dist/img/una.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ Auth::user()->name }}</a>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <!-- MENU -->
          @hasrole('Pelanggan')
          <li class="nav-item">
            <a href="/daftarmenu" class="nav-link">
              <i class="nav-icon far ion-android-apps"></i>
              <p>
                Daftar Menu
                <span class="badge badge-info right"></span>
              </p>
            </a> 
          </li>
          @endrole

          @hasrole('Admin')
          <li class="nav-item">
            <a href="/viewitem" class="nav-link">
              <i class="nav-icon far ion-android-apps"></i>
              <p>
                Kelola Menu
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          
          <li class="nav-item">
            <a href="/history" class="nav-link">
              <i class="nav-icon far ion-cash"></i>
              <p>
                Kelola Transaksi
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="/history" class="nav-link">
              <i class="nav-icon far ion-ios-list"></i>
              <p>
                History Transaksi
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          @endrole
          
          @hasrole('Kasir')

          <li class="nav-item">
            <a href="/pesanan" class="nav-link">
              <i class="nav-icon far ion-android-apps"></i>
              <p>
                Pesanan Masuk
                <span class="badge badge-info right"></span>
              </p>
            </a> 
          </li>

          <li class="nav-item">
            <a href="/daftarmenu" class="nav-link">
              <i class="nav-icon far ion-android-apps"></i>
              <p>
                Daftar Menu
                <span class="badge badge-info right"></span>
              </p>
            </a> 
          </li>

          <li class="nav-item">
            <a href="/history" class="nav-link">
              <i class="nav-icon far ion-ios-list"></i>
              <p>
                History Transaksi
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          @endrole
@hasrole('Admin')
          <li class="nav-header">Kelola Akun</li>
          
          <li class="nav-item">
            <a href=" {{ route('users.index')}} " class="nav-link">
              <i class="nav-icon far ion-person"></i>
              <p>
                Kelola User
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          
          <li class="nav-item">
            <a href=" {{ route('roles.index')}} " class="nav-link">
              <i class="nav-icon far ion-person-stalker"></i>
              <p>
              Kelola Role
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
          
          <li class="nav-item">
            <a href=" {{ route('permissions.index')}} " class="nav-link">
              <i class="nav-icon far ion-unlocked"></i>
              <p>
              Kelola Permission
                <span class="badge badge-info right"></span>
              </p>
            </a>
          </li>
@endrole

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      @yield('content')
  </div>
  <!-- /.content-wrapper -->

  <!-- 
    <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.1
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
  </footer>
  -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>
</body>
</html>